name: 'Install Build Dependencies'
description: 'Update environment with build dependencies'
runs:
  using: "composite"
  steps:
    - name: Install build dependencies
      shell: bash -l {0}
      run: |
        mamba env update -n metgem -f metgem/environment.dev.yml
        if [ "${{ runner.os }}" == "Windows" ]; then
            mamba install pywin32
        elif [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get install -y libfuse2
        elif [ "${{ runner.os }}" == "macOS" ]; then
          npm install -g appdmg
        fi
