name: 'Set up Environment'
description: 'Set up miniconda environment'
inputs:
  use-cached:
    description: "Use cached environment"
    required: false
    default: 'false'
  install-system-deps:
    description: "Install system dependencies"
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Set up environment
      if: ${{ inputs.use-cached == "false" }}
      shell: bash -l {0}
      run: |
        mamba env update -n metgem -f metgem/environment.yml
        mamba env update -n metgem -f metgem/environment.dev.yml
        mamba env update -n metgem -f environment.packaging.yml
        if [ "${{ runner.os }}" == "Windows" ]; then
            mamba install pywin32
        fi
    - name: Install system build dependencies
      if: ${{ inputs.install-system == "true" }}
      shell: bash -l {0}
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get install -y libfuse2
        elif [ "${{ runner.os }}" == "macOS" ]; then
          npm install -g appdmg
        fi
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
