name: 'Set up Environment'
description: 'Set up miniconda environment'
inputs:
  use-cached:
    description: "Use cached environment"
    required: false
    default: 'false'
  install-system-deps:
    description: "Install system dependencies"
    required: false
    default: 'true'
  update:
    description: "Update environment"
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Find mamba command
      shell: bash -el {0}
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "mamba=mamba.bat" >> "$GITHUB_ENV"
        else
          echo "mamba=mamba" >>"$GITHUB_ENV"
        fi
        echo $mamba
    - name: Set up environment
      if: ${{ inputs.use-cached == 'false' }}
      shell: bash -el {0}
      run: |
        $mamba env update -n metgem -f metgem/environment.yml
        $mamba env update -n metgem -f metgem/environment.dev.yml
        $mamba env update -n metgem -f environment.packaging.yml
        if [ "${{ runner.os }}" == "Windows" ]; then
            $mamba install pywin32
        fi
    - name: Install system build dependencies
      if: ${{ inputs.install-system-deps == 'true' }}
      shell: bash -el {0}
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get install -y libfuse2 libegl1 libopengl0 
        elif [ "${{ runner.os }}" == "macOS" ]; then
          npm install -g appdmg
        fi
    - name: Conda info
      shell: bash -el {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Update environment
      shell: bash -el {0}
      if: ${{ inputs.update == 'true' }}
      run: $mamba env update -n metgem -f metgem/environment.yml
    - name: List packages
      shell: bash -el {0}
      run: $mamba list >"packages-${{ runner.os }}.txt"
