name: 'Set up Environment'
description: 'Set up miniconda environment'
inputs:
  update:
    description: "Update cached environment"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash -l {0}
      run: |
        if [ "${{ inputs.update }}" == "true" ]; then
          mamba update -n metgem --all
        else
          mamba env update -n metgem -f metgem/environment.yml
          mamba env update -n metgem -f metgem/environment.dev.yml
          mamba env update -n metgem -f environment.packaging.yml
          if [ "${{ runner.os }}" == "Windows" ]; then
              mamba install pywin32
          fi
        fi
    - name: Install system build dependencies
      shell: bash -l {0}
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get install -y libfuse2
        elif [ "${{ runner.os }}" == "macOS" ]; then
          npm install -g appdmg
        fi
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
