name: Release

on:
  workflow_dispatch:
    inputs:
      linux:
        description: 'Run build on Linux'
        type: boolean
        required: false
        default: true
      windows:
        description: 'Run build on Windows'
        type: boolean
        required: false
        default: true
      macos:
        description: 'Run build on macOS'
        type: boolean
        required: false
        default: true
    
defaults:
  run:
    shell: bash -l {0}
    
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build-release:
    name: Build
    needs: [generate-matrix]
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        os: ${{ fromJSON(needs.generate-matrix.outputs.os) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Update submodules
        run: |
          git submodule init
          git submodule update
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: metgem
          use-mamba: true
          mamba-version: "*"
          channel-priority: strict
          channels: conda-forge,metgem,bioconda
          python-version: ${{ matrix.python-version }}
      - name: Get Cache folder
        id: get-prefix
        run: |
          CONDA_PREFIX=$(python -c "import sys; print(sys.prefix)")
          echo "prefix=$CONDA_PREFIX" >> $GITHUB_OUTPUT
      - name: Cache conda
        if: ${{ !env.ACT }}
        id: cache
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ${{ steps.get-prefix.outputs.prefix }}
          key: ${{ matrix.os }}-${{matrix.python-version}}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('metgem/environment*.yml') }}
      - name: Set up Environment
        uses: ./.github/actions/set_up_env
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Update Environment
        run: mamba update -n metgem --all
        if: steps.cache.outputs.cache-hit == 'true'
      - name: Build
        id: build
        uses: ./.github/actions/build
      - name: Run Tests
        id: tests
        uses: ./.github/actions/tests
      - name: Upload Tests Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: ${{ steps.tests.outputs.log }}
      - name: Get/Create Release
        if: ${{ !env.ACT }}
        id: create-release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          repo: metgem
          owner: metgem
          tag: ${{ steps.build.outputs.tag }}
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ${{ steps.build.outputs.asset-name }}
          asset_name: ${{ steps.build.outputs.asset-basename }}-${{ github.ref }}.${{ steps.build.outputs.asset-ext }}
          asset_content_type: ${{ steps.build.outputs.asset-mimetype }}
          token: ${{ secrets.RELEASE_TOKEN }}

  generate-matrix:
    runs-on: ubuntu-latest
    name: "Generate matrix job specs"
    outputs:
      os: ${{ steps.generate-matrix.outputs.os }}
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            os=()
            if [ "${{ github.event.inputs.linux}}" == "true" ]; then
              os+=('ubuntu')
            fi
            if [ "${{ github.event.inputs.windows}}" == "true" ]; then
              os+=('windows')
            fi
            if [ "${{ github.event.inputs.macos }}" == "true" ]; then
              os+=('macos')
            fi
            os=$(printf ', "%s"' "${os[@]}")
            os="[${os:2}]"
            echo "[INFO] OS selected: $os"
            echo "os=$os" >> $GITHUB_OUTPUT
          else
            echo 'os=["ubuntu","windows","macos"]' >> $GITHUB_OUTPUT
          fi
